/* -------------------------------------------

Copyright ZKA Technologies.

File: xpcom_sms.idl
Purpose: SMS XPCOM interface

------------------------------------------- */

#ifndef __NDK__
#define object class
#define protocol class
#define interface private
#define interface_method

#define CONST const
#define CHAR char
#define INT32 __INT32_TYPE__
#define SIZE_T __SIZE_TYPE__

#define _Output
#define _Input
#define clsid(X)

#warning ! You may be using the clang version of the NDK, please be cautious that some features mayn't be present. !
#endif // !__NDK__

clsid("0943A614-0201-4107-8F8D-E909DF7F53C9")
protocol ISMS
{
interface:
    interface_method INT32 SendMessage(_Input CONST CHAR* bytes, _Input SIZE_T bytes_size);
    interface_method INT32 RecvMessage(_Output CONST CHAR** bytes_in, _Input SIZE_T bytes_size);
};
