##################################################
# ; (C) Mahrouss Logic, 2024, all rights reserved.
# This is the tools makefile.
##################################################

.PHONY: make_hcfs
make_hcfs:
	g++ -I./ -std=c++20 make_hcfs.cxx -o make_hcfs.exe